### ISSUE TITLE
Aspect ratio adapts to the window size.

### ISSUE THREAD

**Issue by JustCryen** [Legend-Master/discord-better-image-viewer#7]
First of all, I love the project!  

Currently the picture stretches based on the Discord window shape.  

https://github.com/user-attachments/assets/26496655-cc38-4f60-bffa-29d3eb40adba

Expected behavior:
Picture remaining in its native aspect ratio regardless of the program window shape.

I'm opening the issue mainly to start tracking it.

**Comment by Legend-Master** [comment]
Hey thanks, I just fixed this several days ago, do you mind trying the one from [github](https://raw.githubusercontent.com/Legend-Master/discord-better-image-viewer/refs/heads/main/BetterImageViewer.plugin.js)? I think the last fixed version has been updated to better discord's site but it didn't have a version bump so the auto update might not work, I have bumped the version yesterday with the gallery fix since then, still need to wait for them to approve the changes manually though

Also see #6

**Comment by JustCryen** [comment]
Okay, the git version is indeed working.  
Sorry about that
